ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: ndi-tty.moreiradj.net
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - secretName: ndi-tty-moreiradj-net-tls
      hosts:
        - ndi-tty.moreiradj.net

image:
  pullPolicy: Always
  tag: latest
