apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "captcha-api.fullname" . }}
  labels:
    {{- include "captcha-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "captcha-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
