{
 "title": "NDI TTY",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "NodeJS Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{app=\"captcha-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"captcha-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{app=\"captcha-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_heap_bytes{app=\"captcha-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{app=\"captcha-api\",kind=\"minor\"}[1m])",
     "legendFormat": "Minor"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{app=\"captcha-api\",kind=\"incremental\"}[1m])",
     "legendFormat": "Incremental"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{app=\"captcha-api\",kind=\"major\"}[1m])",
     "legendFormat": "Major"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{app=\"captcha-api\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{app=\"captcha-api\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{app=\"captcha-api\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waldo Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "charlie_successes{app=\"captcha-api\"}",
     "legendFormat": "Waldo Found"
    },
    {
     "expr": "charlie_fails{app=\"captcha-api\"}",
     "legendFormat": "Failed to find Waldo"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"captcha-api\"} |= ``"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"frontend\"} |= ``"
    }
   ]
  }
 ]
}